### ISSUE TITLE
Registro y Autenticación

### ISSUE THREAD

**Issue by AdrianSerranoRojas** [AdrianSerranoRojas/Music-Player-Musikfy#49]
User Stories

- [ ] Autentificación de Usuario #47
- [ ] Guardado de credenciales #46 
- [ ] Cierre de sesión de usuario #40 
- [ ] Registro de Usuarios #39 
- [ ] Recuperación de password #38
