### ISSUE TITLE
Visualización y gestión de usuarios/artistas

### ISSUE THREAD

**Issue by gcachonc** [AdrianSerranoRojas/Music-Player-Musikfy#50]
- [ ] vista de usuario #29 
- [ ] seguir a otros usuarios #31 
- [ ] visualización de seguidores #32 
- [ ] visualización de siguiendo #33
