### ISSUE TITLE
Pantalla Home principal

### ISSUE THREAD

**Issue by AdrianSerranoRojas** [AdrianSerranoRojas/Music-Player-Musikfy#52]
User Stories

- [ ] Pantalla home básica #37 
- [ ] Sección “Playlists populares” en pantalla home #8 
- [ ] Sección “Artistas populares” en pantalla  home #23 
- [ ] Sección “Playlists que sigo” en pantalla home #26
