### ISSUE TITLE
Gestión de la cuenta

### ISSUE THREAD

**Issue by RoyerMateu** [AdrianSerranoRojas/Music-Player-Musikfy#53]
- [ ] Visualización de información de usuario #19 
- [ ] Edición de información de usuario  #15 
- [ ] Cambio de contraseña de usuario #7
