### ISSUE TITLE
Publicación, visualización y gestión de playlists

### ISSUE THREAD

**Issue by gcachonc** [AdrianSerranoRojas/Music-Player-Musikfy#55]
- [ ] Listado de playlists #5 
- [ ] Orden manual en listado de playlists #9 
- [ ] Creación de playlists #11 
- [ ] Vista de playlists #12 
- [ ] Seguir playlist en visualización de Playlists #14 
- [ ] Cambio de privacidad en vista de Playlist #16 
- [ ] Añadir canciones dentro de Playlist desde vista Playlist #18 
- [ ] Menú “Opciones” dentro de Playlist #21
